config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :bookings, only: %i[new create index destroy]

  resources :posts, only: %i[new create destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  # belongs_to :game

  validates :start_date, :start_time, :end_time, presence: true

  # validate :end_date_after_start_date

  # private

  # def end_date_after_start_date
  #   return if end_date.blank? || start_date.blank?

  #   if end_date < start_date
  #     errors.add(:end_date, 'must be after the start date')
  #   end
  # end
end

app/models/game.rb
class Game < ApplicationRecord
  # has_many :bookings
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user)
  end
  
  def new
    # @game = Game.find(params[:game_id])
    @booking = Booking.new
  end

  def create
    # @game = Game.find(params[:game_id])
    @booking = Booking.new(booking_params)
    # @booking.game = @game
    @booking.user = current_user
    if @booking.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :start_date, :start_time, :end_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all.order("created_at DESC")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/bookings/_new-booking-form.html.erb
<%= simple_form_for @booking do |f| %>
  <%= f.input :start_date,
  label: 'Start Date',
  as: :string,
  input_html: { class: 'datepicker' },
  html5: true,
  start_day: Date.today.day %>

  <%= f.input :start_time,
  label: 'Start Time',
  as: :string,
  input_html: { class: 'timepicker' },
  html5: true %>

   <%= f.input :end_time,
  label: 'End Time',
  as: :string,
  input_html: { class: 'timepicker' },
  html5: true %>

  <%= f.submit 'Confirm booking', class: 'btn btn-success' %>
  <%= link_to 'Cancel', root_path, class: 'btn btn-outline-danger' %>
<% end %>

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
  <p><%= booking.start_date.strftime("%d of %B, %Y") %></p>
  <p><%= booking.start_time.strftime("%I:%M %p") %></p>
  <p><%= booking.end_time.strftime("%I:%M %p") %></p>
  <%= link_to 'Cancel this booking', booking_path(booking), method: :delete, data: {confirm: "Cancel booking?"} %>
<% end %>

<%= link_to 'Back', root_path, class: 'btn btn-outline-danger' %>

app/views/bookings/new.html.erb
<div class="container d-flex justify-content-center align-items-center h-50">
  <div class="row w-25">
    <div class="col">
      <h1>New Booking</h1>
      <%= render 'new-booking-form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<html>
<head>
  <title>TableTennis</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render 'components/nav' %>
  <%= render 'shared/flashes' %>

  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class='d-flex py-5 justify-content-center'>
    <h2 class="px-3">Message Board</h2>
    <%= link_to new_post_path, class: 'btn btn-sm btn-primary' do %>
      <i class="fas fa-plus"></i> New message
    <% end %>
  </div>

  <% @posts.each do |post| %>
  <div class="card my-4 p-4 shadow-sm col-sm-8 col-lg-6 mx-auto">
      <h3><%= post.title %></h3>
      <span class="text-muted"><strong>Posted by: </strong><em><%= post.user.email.split('@')[0] %></em></span>
      <p><%= post.content %></p>
      <% if post.user == current_user %>
        <%= link_to post_path(post), method: :delete, data: {confirm: "Remove post?"}, class: 'text-danger' do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      <% end %>
  </div>
  <% end %>
</div>

app/views/posts/_new-post-form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title,
  label: 'Title' %>

  <%= f.input :content,
  label: 'Content' %>

  <%= f.submit 'Submit', class: 'btn btn-success' %>
  <%= link_to 'Cancel', root_path, class: 'btn btn-outline-danger' %>
<% end %>

app/views/posts/new.html.erb
<div class="container d-flex justify-content-center align-items-center h-50">
  <div class="row w-25">
    <div class="col">
      <h1>New Post</h1>
      <%= render 'new-post-form' %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>